-- Better Auth core schema.
--
-- Written as SQL rather than generated by `auth generate`, for two reasons:
--
--   1. The CLI pulls in `better-sqlite3` and tries to build it natively,
--      which fails on a Bun-only machine with no node-gyp — even though we
--      only ever target Postgres.
--   2. A migration you can read in a diff is worth more than one produced
--      by a tool.
--
-- ── Every identifier is double-quoted, and that is load-bearing ──────────
--
-- Better Auth's Kysely adapter uses its field names verbatim, so the
-- columns are camelCase: "emailVerified", "userId", "banExpires".
-- Postgres folds *unquoted* identifiers to lower case, which would create
-- "emailverified" and then fail every sign-up with
--
--     column "emailVerified" of relation "user" does not exist
--
-- so `"emailVerified"` must be quoted, in the DDL and in every index and
-- foreign key that mentions it. Do not "tidy" the quotes away.
--
-- This schema is verified by a real sign-up / sign-in / session round trip
-- against Postgres; see README, "Verifying the auth schema".
--
-- "role", "banned", "banReason" and "banExpires" come from the `admin`
-- plugin. `role` is also declared in `auth.ts` as an additionalField; the
-- two agree on the name.

CREATE TABLE IF NOT EXISTS "user" (
  "id"            text PRIMARY KEY,
  "name"          text        NOT NULL,
  "email"         text        NOT NULL UNIQUE,
  "emailVerified" boolean     NOT NULL DEFAULT false,
  "image"         text,
  "createdAt"     timestamptz NOT NULL DEFAULT now(),
  "updatedAt"     timestamptz NOT NULL DEFAULT now(),

  -- admin plugin
  "role"          text,
  "banned"        boolean,
  "banReason"     text,
  "banExpires"    timestamptz
);

CREATE TABLE IF NOT EXISTS "session" (
  "id"         text PRIMARY KEY,
  -- Sessions are looked up and expired on this column constantly.
  "expiresAt"  timestamptz NOT NULL,
  "token"      text        NOT NULL UNIQUE,
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  "updatedAt"  timestamptz NOT NULL DEFAULT now(),
  "ipAddress"  text,
  "userAgent"  text,
  "userId"     text        NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "session_expiresAt_idx" ON "session" ("expiresAt");

CREATE TABLE IF NOT EXISTS "account" (
  "id"                    text PRIMARY KEY,
  -- A credential account uses providerId = 'credential', accountId = user.id.
  "accountId"             text        NOT NULL,
  "providerId"            text        NOT NULL,
  "userId"                text        NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  -- scrypt hash for email/password sign-in. Never a plaintext password.
  "password"              text,
  "createdAt"             timestamptz NOT NULL DEFAULT now(),
  "updatedAt"             timestamptz NOT NULL DEFAULT now()
);

-- Better Auth resolves an account by (providerId, accountId).
CREATE INDEX IF NOT EXISTS "account_provider_account_idx"
  ON "account" ("providerId", "accountId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");

CREATE TABLE IF NOT EXISTS "verification" (
  "id"         text PRIMARY KEY,
  "identifier" text        NOT NULL,
  "value"      text        NOT NULL,
  "expiresAt"  timestamptz NOT NULL,
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  "updatedAt"  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "verification_identifier_idx"
  ON "verification" ("identifier");

-- One place to ask "does this user own the shop", so the API route guard and
-- any future query agree.
CREATE OR REPLACE FUNCTION is_admin(check_user_id text) RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM "user"
     WHERE "id" = check_user_id
       AND "role" = 'admin'
       AND "banned" IS NOT TRUE
  );
$$ LANGUAGE sql STABLE;
