/**
 * Generates `src/styles/theme-blush.css` — a Skeleton v5 theme built from
 * perceptual OKLCH ramps rather than hand-picked hex values, so every
 * scale step is evenly spaced in lightness.
 *
 * Run after changing a hue below:  bun scripts/build-theme.ts
 *
 * Why a generator: Skeleton needs 11 steps × 6 colour scales. Typing them
 * by hand is how you end up with a 600 that is visibly greener than its
 * 500 neighbours.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/* ── Brand inputs ──────────────────────────────────────────────────────
   Hues in OKLCH degrees. Chroma is the ceiling; the ramp eases off it at
   the light and dark ends where wide gamut reads as neon.                */

const RAMPS = {
  primary: { hue: 358, chroma: 0.13, label: 'rose' },
  secondary: { hue: 330, chroma: 0.15, label: 'petal magenta' },
  tertiary: { hue: 148, chroma: 0.07, label: 'eucalyptus' },
  success: { hue: 152, chroma: 0.12, label: 'sage' },
  warning: { hue: 78, chroma: 0.14, label: 'butter' },
  error: { hue: 22, chroma: 0.16, label: 'clay' },
} as const;

/** Lightness anchors for steps 50 → 950. 500 is the brand colour. */
const LIGHTNESS: Record<number, number> = {
  50: 0.975,
  100: 0.955,
  200: 0.9,
  300: 0.82,
  400: 0.72,
  500: 0.62,
  600: 0.535,
  700: 0.455,
  800: 0.38,
  900: 0.315,
  950: 0.255,
};

/** Chroma follows lightness — pale at the top, rich in the middle. */
function chromaAt(base: number, l: number): number {
  const t = (l - 0.255) / (0.975 - 0.255); // 0 at 950, 1 at 50
  const bell = Math.sin(Math.PI * Math.min(1, Math.max(0, t)));
  return Number((base * (0.25 + 0.75 * bell)).toFixed(4));
}

const round = (n: number, p = 4) => Number(n.toFixed(p));

const oklch = (hue: number, l: number, c: number) =>
  `oklch(${round(l, 3)} ${round(c)} ${hue})`;

/* ── Render ──────────────────────────────────────────────────────────── */

const steps = Object.keys(LIGHTNESS).map(Number).sort((a, b) => a - b);

const scaleBlocks = Object.entries(RAMPS)
  .map(([name, { hue, chroma }]) => {
    const lines = steps
      .map((step) => {
        const l = LIGHTNESS[step]!;
        const c = chromaAt(chroma, l);
        return `\t--color-${name}-${step}: ${oklch(hue, l, c)};`;
      })
      .join('\n');
    return `/* ${name} — ${(RAMPS as Record<string, { label: string }>)[name]!.label} */\n${lines}`;
  })
  .join('\n\n');

/**
 * Surface is a warm, faintly pink neutral rather than a true grey — pure
 * grey next to rose reads dirty, and this is the page background.
 */
const surfaceHue = 22;
const surfaceChroma = 0.014;
const surfaceBlock = [
  '/* surface — warm blush neutral */',
  ...steps.map((step) => {
    const l = LIGHTNESS[step]!;
    // Pull the darkest steps toward the ink hue so text and bg agree.
    const hue = surfaceHue + (l < 0.45 ? 8 : 0);
    return `\t--color-surface-${step}: ${oklch(hue, l, chromaAt(surfaceChroma, l))};`;
  }),
].join('\n');

const css = `/**
 * Skeleton theme — "blush"
 *
 * Generated by scripts/build-theme.ts. Edit that file, not this one.
 *
 * A soft rose-and-petal palette on a warm, faintly pink neutral, with a
 * muted eucalyptus tertiary as the complement. Every step is an even
 * perceptual step in OKLCH, so 400 → 500 → 600 read as one family.
 */

[data-theme='blush'] {
	${surfaceBlock}

${scaleBlocks}

	/* Page background. Warm, not white. */
	--color-root-bg-light: oklch(0.985 0.008 25);
	--color-root-bg-dark: oklch(0.19 0.02 15);

	/* Type */
	--typo-heading--font-family: 'Fraunces Variable', 'Fraunces', Georgia, serif;
	--typo-base--font-family: 'Instrument Sans Variable', 'Instrument Sans', system-ui, sans-serif;
	--typo-anchor--font-family: inherit;

	/* Fraunces' optical size axis wants headings set a little tighter and
	   heavier than the default scale assumes. */
	--typo-heading--font-weight: 500;
	--typo-heading--line-height: 1.1;
	--text-scaling: 1.05;

	/* Corners. Slightly rounded — crochet edges are soft, but a fully
	   circular radius would read as a bubble. */
	--radius-container: 0.5rem;
	--radius-base: 0.375rem;
	--radius-factor: 1;
	--size-selector: 0.25rem;
	--size-field: 0.25rem;

	/* Vertical rhythm. */
	--spacing: 0.27rem;
}
`;

const out = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'styles',
  'theme-blush.css',
);
await mkdir(dirname(out), { recursive: true });
await writeFile(out, css, 'utf8');
console.log(`✓ wrote ${out}`);
