/**
 * `/api/admin/products` — the catalogue list and the create endpoint.
 *
 * `includeHidden` defaults to **true** here, unlike the storefront. The panel
 * needs to see hidden pieces so they can be unhidden; the shop must not. That
 * asymmetry was in the deleted API and is preserved deliberately.
 *
 * ## Why publishing is not called from here
 *
 * The old API ended every catalogue write by firing a Cloudflare deploy hook.
 * That was correct when a database write and a live site were two different
 * things. They are not any more: the site is built from `catalog.json`, and
 * `catalog.json` is regenerated by an explicit `publish`. So a write here
 * changes the local database and *nothing else* — the site does not change
 * until someone presses Publish.
 *
 * That is a real change in the owner's workflow, so the panel says so
 * explicitly rather than letting "Saved" imply "live". See
 * `lib/publish-client.ts` and the footer in `+page.svelte`.
 */

import { productInputSchema, type Category } from '@crochet/shared';
import { createProduct, getProductById, listProducts, replaceProductImages, transact } from '$lib/db';
import { fail, isUniqueViolation, ok, parseBody, unexpected } from '$lib/server/respond';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = ({ url }) => {
  try {
    const category = url.searchParams.get('category');
    const q = url.searchParams.get('q');

    return ok(
      listProducts({
        includeHidden: url.searchParams.get('includeHidden') !== 'false',
        ...(category ? { category: category as Category } : {}),
        ...(q ? { search: q.slice(0, 80) } : {}),
      }),
    );
  } catch (err) {
    return unexpected(err, 'GET /api/admin/products');
  }
};

export const POST: RequestHandler = async ({ request }) => {
  const parsed = await parseBody(request, productInputSchema);
  if ('response' in parsed) return parsed.response;
  const input = parsed.data;

  try {
    const id = transact(() => {
      const created = createProduct({
        slug: input.slug,
        name: input.name,
        tagline: input.tagline,
        description: input.description,
        priceCents: input.priceCents,
        compareAtCents: input.compareAtCents,
        category: input.category,
        images: input.images.map((i) => i.url),
        details: input.details,
        stock: input.stock,
        madeToOrder: input.madeToOrder,
        hidden: input.hidden,
        sortOrder: input.sortOrder,
      });

      // A create with external images should not leave them unattributed.
      if (input.images.length > 0) replaceProductImages(created, input.images);

      return created;
    });

    return ok({ id, product: getProductById(id) }, 201);
  } catch (err) {
    if (isUniqueViolation(err) && /products\.slug/i.test(String(err))) {
      return fail('That URL slug is already taken.', 409, {
        slug: 'Already in use — add something to the end',
      });
    }
    return unexpected(err, 'POST /api/admin/products');
  }
};
