/**
 * Seed the local catalogue with the demo shop.
 *
 * The data is the original `apps/api/scripts/seed-data.ts`, carried over
 * unchanged. It is plain data with no side effects, so the same definition
 * serves this seed and any offline build. One definition means the demo shop
 * is the same shop everywhere.
 *
 * The promotion is generated by the real `banner-engine`, not hard-coded — the
 * same thing the API did. That means a fresh install exercises the generator,
 * so if promotion generation breaks it shows up immediately rather than the
 * first time somebody tries to run a sale.
 *
 * `ageDays` is honoured rather than discarded. The generator scores products
 * partly on how long they have been listed (`ageInDays` in the engine), so
 * backdating `created_at` is what gives it realistic signals to work with
 * instead of twelve products all born the same second.
 *
 *   bun run seed          # refuses to run over existing data
 *   bun run seed --force  # wipes the catalogue first
 */

import { generateBanner } from '../src/lib/banner-engine.ts';
import { PRODUCTS } from './seed-data.ts';
import {
  createBanner,
  createProduct,
  db,
  deleteBanner,
  deleteProduct,
  listProducts,
  nowIso,
  transact,
} from '../src/lib/db.ts';

const force = process.argv.includes('--force');

if (listProducts({ includeHidden: true }).length > 0 && !force) {
  console.error(
    '\n✗ There is already a catalogue in data/catalog.sqlite.\n' +
      '  Seeding would mix demo pieces with your own. Use --force to wipe it first,\n' +
      '  or just open the panel — an empty shop is a perfectly good shop.\n',
  );
  process.exit(1);
}

if (force) {
  transact(() => {
    for (const p of listProducts({ includeHidden: true })) deleteProduct(p.id);
    for (const b of db.query<{ id: string }, []>(`SELECT id FROM banners`).all()) {
      deleteBanner(b.id);
    }
  });
  console.log('  – cleared the existing catalogue');
}

/* ── Products ─────────────────────────────────────────────────────────── */

const seeded = transact(() =>
  PRODUCTS.map((p) => {
    // The seed carries its own stable ids so the data stays recognisable, and
    // backdates creation so the generator has an age to work with.
    const id = p.id;
    const createdAt = new Date(Date.now() - p.ageDays * 86_400_000).toISOString();

    createProduct({
      id,
      slug: p.slug,
      name: p.name,
      tagline: p.tagline,
      description: p.description,
      priceCents: p.priceCents,
      compareAtCents: p.compareAtCents,
      category: p.category,
      images: p.images,
      details: p.details,
      stock: p.stock,
      madeToOrder: p.madeToOrder,
      hidden: p.hidden,
      sortOrder: p.sortOrder,
      createdAt,
    });

    return id;
  }),
);

/* ── One promotion, generated ──────────────────────────────────────────── */

const products = listProducts({ includeHidden: true });
const generated = generateBanner(products, { maxProducts: 4 });

if (generated) {
  const { input, rationale } = generated;

  createBanner({
    id: crypto.randomUUID(),
    ...input,
    status: 'live',
    // A generated campaign with no window would be live forever, which is not
    // what the seed is demonstrating. Seven days, like a real drop.
    startsAt: nowIso(),
    endsAt: new Date(Date.now() + 7 * 86_400_000).toISOString(),
    rationale,
  });

  console.log(
    `  ✓ promotion "${input.name}" — ${input.percentOff}% off, ` +
      `${input.productIds.length} pieces, code ${input.code ?? 'none'}`,
  );
}

console.log(`\n✓ ${seeded.length} products seeded into data/catalog.sqlite\n`);
